# Dockerfile.fastapi
FROM python:3.9-buster

WORKDIR /app_fastapi

COPY requirements.txt /app_fastapi

RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
