version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    restart: on-failure
    volumes:
      - .:/app
      - ./logs:/app/logs

  fastapi_app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app_fastapi
